records:
  - www
  - api

listeners:
  http:
    port: 80
    protocol: http
    default_targetgroup: default

securityGroups:
  loadbalancer:
    -
      rules:
        -
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
      ips:
        - 0.0.0.0/0
